first commit
bcgov/nr-bcws-wfprev pull request #1
Opened 2024-09-04 04:23 UTC by yzlucas

2024-09-04 17:00 UTC, ssylver93 commented on client/wfprev/.vscode/extensions.json
> +{
.vscode files should be gitignored like in WFNEWS

2024-09-04 17:09 UTC, ssylver93 requested changes
Just a couple of comments on files I think shouldn't be included, looks good otherwise

2024-09-04 17:09 UTC, ssylver93 commented on client/wfprev/src/assets/.gitkeep
Empty file should be deleted I feel?

2024-09-04 17:09 UTC, ssylver93 commented on client/wfprev/.vscode/launch.json
> +{
Same for this file

2024-09-04 17:09 UTC, ssylver93 commented on client/wfprev/.vscode/tasks.json
> +{
Same for this file as well

2024-09-05 05:51 UTC, yzlucas commented
@ssylver93  thanks, modify the gitingore file to get rid of that folder
@sukhpalp  I have updated to use angular 18 now, the duplicate "db" was an accident, I used it for local test only and I have removed the previous one. The 01_00_00/01 create table thing is for testing the liquibase changes success or not, I think we can modify the changelog.json to not excute it if needed.

2024-09-05 20:21 UTC, yzlucas commented on db/scripts/01_00_00/01/ddl/tables/APP_WFPREV.EXAMPLE_CODE.sql
Not necessary, I can keep it on my local. I have removed it and update the changelog.json

2024-09-06 06:20 UTC, merged