Wfprev 46
bcgov/nr-bcws-wfprev pull request #74
Opened 2024-09-20 16:40 UTC by yzlucas

2024-09-24 05:30 UTC, yzlucas commented
@vivid-cpreston  Shall I reference the build-full-environment.yml from WFHR for the deploy.yml here?

2024-09-25 18:10 UTC, ssylver93 commented on terraform/alb.tf
> +  name                 = "wfprev-payroll-api-${var.TARGET_ENV}"
Should this be changed from wfprev-payroll-api to wfprev-api?

2024-09-25 18:13 UTC, ssylver93 requested changes
One comment about wfprev-payroll-api naming

2024-09-25 18:43 UTC, yzlucas commented
@sukhpalp @ssylver93  
Thanks, cleaned up after our touch-base

2024-09-25 20:45 UTC, merged